### ISSUE TITLE
Nuxt fails to load 

### ISSUE THREAD

**Issue by robokozo** [wobsoriano/numix#1]
Just testing out the getting started instructions and I get the following error when running `nuxt dev`

I get the following warning:
```
'D:/git/numix-test/.nuxt/numix-handler.mjs' is imported by virtual:#internal/nitro/virtual/server-handlers, but could not be resolved – treating it as an external dependency
```

I get the following error:
```
[worker reload] [worker init] Cannot find module 'D:\.nuxt\numix-handler.mjs' imported from D:\git\numix-test\.nuxt\dev\index.mjs  
```

**Comment by wobsoriano** [comment]
I forgot to add,  you need at least 1 page for the `pages:extend` nuxt hook to emit something.

**Comment by wobsoriano** [comment]
Fixed in latest versions
