### ISSUE TITLE
Loading data in index.vue not possible

### ISSUE THREAD

**Issue by maoberlehner** [wobsoriano/numix#4]
Problem:

Using this pluin within the root `index.vue` file leads to a 500 error `Cannot read properties of null`.

Reproduction:

- Create a `pages/index.vue` File
- Add `loader` and `userLoaderData()`

See: https://stackblitz.com/edit/nuxt-starter-mwn1xp?file=pages%2Findex.vue

Looking forward to using this plugin!

**Comment by wobsoriano** [comment]
Fixed! Thanks

https://stackblitz.com/edit/nuxt-starter-fo7snz?file=pages%2Findex.vue
