### ISSUE TITLE
question about numix and nuxt

### ISSUE THREAD

**Issue by Hebilicious** [wobsoriano/numix#6]
Hi wob, sorry for opening an issue here but I thought it would be fast to reach you that way.
I'm a big fan of your libraries in general, and just stumbled upon this one.
I did not know it existed, and end-up doing something very similar with

https://github.com/Hebilicious/form-actions-nuxt

I recently joined the unjs team, and I hope that we'll be able to add this pattern in Nuxt core one day.
Would you like to collaborate together ?

**Comment by wobsoriano** [comment]
Hey man!

I saw your module recently and I love it.

Numix implementation is simple compared to form-actions-nuxt. It basically just uses vue/compiler-core in Nitro and keeps the contents of `<script></script>` and calls it inside an `eventHandler`. It doesn't support nested routes yet.

I'd love to collaborate!
